import 'package:flutter/material.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

class LanguageProvider extends ChangeNotifier {
  final FlutterSecureStorage _storage = const FlutterSecureStorage();
  Locale _locale = const Locale('ar');

  Locale get locale => _locale;
  bool get isRTL => _locale.languageCode == 'ar';

  LanguageProvider() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final savedLang = await _storage.read(key: 'language_code');
    if (savedLang != null) {
      _locale = Locale(savedLang);
      notifyListeners();
    }
  }

  Future<void> setLanguage(String languageCode) async {
    _locale = Locale(languageCode);
    notifyListeners();
    try {
      await _storage.write(key: 'language_code', value: languageCode);
    } catch (e) {
      debugPrint('Failed to save language: $e');
    }
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Halawat Lil Moaamalat',
      'app_title_ar': 'حلوات للمعاملات',
      'app_subtitle':
          'Store ERP, CRM, distribution, stock, sales, and invoices',
      'login': 'Login',
      'email': 'Email Address',
      'email_or_phone': 'Email or phone number',
      'password': 'Password',
      'dashboard': 'Dashboard',
      'reports': 'Reports',
      'orders': 'Orders',
      'crm': 'CRM',
      'dispatch': 'Dispatch',
      'approvals': 'Approvals',
      'onboard_shop': 'Onboard Shop',
      'catalog': 'Catalog',
      'inventory': 'Inventory',
      'procurement': 'Procurement',
      'promotions': 'Promotions',
      'notifications': 'Notifications',
      'audit_log': 'Audit Log',
      'invoices': 'Invoices',
      'sales_reps': 'Sales Reps',
      'settings': 'Settings',
      'logout': 'Logout',
      'language': 'Language',
      'arabic': 'العربية',
      'english': 'English',
      'loading': 'Loading...',
      'success': 'Success',
      'error': 'Error',
      'save': 'Save',
      'cancel': 'Cancel',
      'reset_password': 'Reset password',
      'reset_password_for': 'Reset password for {name}',
      'password_reset_explanation':
          'The user will use this password the next time they sign in.',
      'new_password': 'New password',
      'confirm_password': 'Confirm password',
      'password_min_8': 'Password must be at least 8 characters',
      'confirm_password_required': 'Confirm the password',
      'passwords_do_not_match': 'Passwords do not match',
      'password_updated_for': 'Password updated for {name}.',
      'password_update_failed': 'Failed to update password.',
      'login_required': 'Please sign in before placing an order.',
      'order_place_failed': 'Unable to place the order. Your cart was kept.',
      'order_placed': 'Order placed',
      'order_created_waiting_approval':
          'Order {order} was created and is waiting for admin approval.',
      'scheduled_delivery': 'Scheduled delivery',
      'ok': 'OK',
      'shopping_cart': 'Shopping cart',
      'cart_empty': 'Your cart is empty',
      'cart_empty_hint': 'Go to the catalog to add products.',
      'unit': 'unit',
      'subtotal': 'Subtotal',
      'stock_limit_reached': 'Cannot exceed the available stock.',
      'total_quantity': 'Total quantity',
      'place_order': 'Place order',
      'cash_balance_outstanding': 'Cash balance and outstanding',
      'total_ordered': 'Total ordered',
      'cash_collection_status': 'Cash collection status',
      'no_payment_transactions': 'No payment transactions found',
      'collected': 'Collected',
      'cash_collected_by_responsible':
          'Cash is collected by the driver or responsible staff.',
      'ordered_items': 'Ordered items',
      'no_order_items': 'No ordered items were returned.',
      'settings_load_failed': 'Unable to load settings',
      'logo_upload_failed': 'Unable to upload the company logo.',
      'company_settings_saved': 'Company settings saved.',
      'company_settings_save_failed': 'Unable to save company settings',
      'otp_login_enabled_message': 'OTP login is now enabled.',
      'otp_login_disabled_message': 'OTP login is now disabled.',
      'otp_update_failed': 'Unable to update OTP login',
      'company_profile': 'Company profile',
      'login_and_otp': 'Login and OTP',
      'upload_company_logo': 'Upload company logo',
      'invoice_logo_hint':
          'This logo and company information print on invoices.',
      'company_name': 'Company name',
      'tax_id': 'Tax ID / ICE',
      'otp_login': 'OTP login',
      'otp_login_control_description':
          'Allow registered users in this company to sign in by SMS or WhatsApp code.',
      'otp_existing_user_explanation':
          'OTP never creates a second account. A verified code signs the registered phone number into its existing account.',
      'create': 'Create',
      'add': 'Add',
      'delete': 'Delete',
      'search': 'Search',
      'import': 'Import',
      'export': 'Export',
      'bulk_import': 'Bulk Import',
      'bulk_export': 'Bulk Export',
      'categories': 'Categories',
      'brands': 'Brands',
      'products': 'Products',
      'retailers': 'Retailers',
      'customers': 'Customers',
      'accounts': 'Accounts',
      'recent_activity': 'Recent Activity',
      'sales_performance': 'Sales Performance',
      'target_progress': 'Target Progress',
      'user_role': 'User Role',
      'name': 'Name',
      'phone': 'Phone Number',
      'manager': 'Manager',
      'sales_rep': 'Sales Rep',
      'distributor': 'Distributor',
      'retailer': 'Retailer',
      'create_account': 'Create User Account',
      'low_stock': 'Low Stock',
      'adjust_stock': 'Adjust Stock',
      'reason': 'Reason',
      'amount': 'Amount',
      'status': 'Status',
      'due_date': 'Due Date',
      'mark_all_read': 'Mark All Read',
      'no_items': 'No items found',
      'add_category': 'Add Category',
      'category_name': 'Category Name',
      'upload_image': 'Upload Image',
      'image_uploaded': 'Image Uploaded',
      'add_brand': 'Add Brand',
      'brand_name': 'Brand Name',
      'upload_logo': 'Upload Logo',
      'logo_uploaded': 'Logo Uploaded',
      'add_product': 'Add Product',
      'product_name': 'Product Name',
      'base_price': 'Base Price',
      'price': 'Price',
      'category': 'Category',
      'brand': 'Brand',
      'new_promotion': 'New Promotion',
      'type': 'Type',
      'percentage': 'Percentage',
      'fixed_amount': 'Fixed Amount',
      'bulk_tier': 'Bulk Tier',
      'buy_x_get_y': 'Buy X Get Y',
      'priority': 'Priority',
      'all': 'All',
      'paid': 'Paid',
      'unpaid': 'Unpaid',
      'outstanding': 'Outstanding',
      'gross_sales': 'Gross Sales',
      'top_retailers': 'Top Retailers',
      'top_products': 'Top Products',
      'sales_trend': 'Sales Trend',
      'detailed_reports': 'Detailed Reports',
      'target_scope': 'Target Scope',
      'product_specific': 'Product specific',
      'brand_specific': 'Brand specific',
      'category_specific': 'Category specific',
      'sign_out': 'Sign Out',
      'sign_out_confirm': 'Are you sure you want to sign out?',
      'press_back_exit': 'Press back again to exit',
      'back_to_home': 'Back to main page',
      'retailer_portal': 'Retailer Portal',
      'distributor_portal': 'Distributor Portal',
      'representative_workspace': 'Representative Workspace',
      'assigned_retailers': 'Assigned Retailers',
      'orders_cash': 'Orders & Cash',
      'onboard': 'Onboard',
      'cart': 'Cart',
      'payments': 'Payments',
      'refresh': 'Refresh',
      'main': 'Main',
      'management': 'Management',
      'system': 'System',
      'address': 'Address',
      'latitude': 'Latitude',
      'longitude': 'Longitude',
      'required': 'Required',
      'invalid': 'Invalid',
      'verify_location_on_map': 'Verify Location on Map',
      'verify_shop_location': 'Verify Shop Location',
      'close': 'Close',
      'use_current_location': 'Use Current Location',
      'use_this_pin': 'Use This Pin',
      'location_help':
          'Tap the map to move the pin, or use the device location.',
      'location_services_disabled':
          'Location services are disabled. Turn on GPS and try again.',
      'turn_on_location_retry':
          'Location settings opened. Turn on GPS, then tap Use Current Location again.',
      'location_permission_denied': 'Location permission was not granted.',
      'location_permission_settings':
          'Location permission is blocked. Enable it in Android app settings.',
      'map_unavailable':
          'Map is not available yet. Rotate or reopen this view.',
      'no_delivery_coordinates': 'No delivery coordinates saved',
      'gps_unavailable': 'GPS: unavailable',
      'delivery_pin_saved': 'Delivery pin saved',
      'location_needed': 'Location needed',
      'locating_driver': 'Locating driver position...',
      'direct_route_preview': 'Direct route preview',
      'open_road_navigation': 'Open road navigation',
      'navigation_open_failed': 'Could not open a navigation app.',
      'retry_location': 'Retry location',
      'password_login': 'Password',
      'phone_otp': 'Phone OTP',
      'new_retailer': 'New Retailer?',
      'register_here': 'Register Here',
      'phone_number': 'Phone number',
      'six_digit_code': '6-digit code',
      // Order Statuses
      'status_pending': 'Pending',
      'status_approved': 'Approved',
      'status_in_transit': 'In Transit',
      'status_delivered': 'Delivered',
      'status_cancelled': 'Cancelled',
      // Payment Statuses
      'payment_unpaid': 'Unpaid',
      'payment_partially_paid': 'Partially Paid',
      'payment_paid': 'Paid',
      // Order details and labels
      'order_label': 'Order',
      'client_information': 'Client Information',
      'coordinates': 'Coordinates',
      'assigned_to': 'Assigned To',
      'awaiting_assignment': 'Awaiting assignment',
      'order_items': 'Order Items',
      'grand_total': 'Grand Total',
      'payment_summary': 'Payment Summary',
      'total_amount': 'Total Amount',
      'remaining_balance': 'Remaining Balance',
      'delivery_proof': 'Delivery Proof',
      'no_delivery_proof': 'No delivery proof attached',
      'delivery_photo': 'Delivery Photo',
      'failed_load_image': 'Failed to load image',
      'delivery_signature': 'Delivery Signature',
      'failed_load_signature': 'Failed to load signature',
      'notes': 'Notes',
      'product': 'Product',
      'qty': 'Qty',
      'unit_price': 'Unit Price',
      'total': 'Total',
      'item': 'item',
      'items': 'items',
      // CRM
      'pin': 'Pin',
      'missing': 'Missing',
      'recent_orders': 'Recent Orders',
      'no_orders_yet': 'No orders yet',
      'open_orders': 'Open orders',
      'pin_missing': 'Missing pin',
      'crm_load_failed': 'CRM load failed',
      'search_crm': 'Search CRM',
      'clear': 'Clear',
      'due_status': 'Due',
      'approve_account': 'Approve',
      'account_approved': 'Account approved successfully.',
      'approval_failed': 'Account approval failed',
      'registrations': 'Registrations',
      'pending_registrations': 'Pending registrations',
      'registration_review_help':
          'Review new retailer accounts before they can sign in.',
      'search_registrations': 'Search by shop, email, phone, or address',
      'no_pending_registrations': 'No registrations waiting',
      'no_pending_registrations_help':
          'New retailer applications will appear here for your approval.',
      'approve_registration': 'Approve registration',
      'approve_registration_confirm':
          'Approve {name} and allow this account to sign in?',
      'reject_registration': 'Reject registration',
      'reject_registration_confirm':
          'Reject {name}? The account will remain inactive.',
      'rejection_reason': 'Reason (optional)',
      'rejection_reason_hint': 'Add a note for the audit log',
      'registration_rejected': 'Registration rejected.',
      'rejection_failed': 'Registration rejection failed',
      'submitted': 'Submitted',
      'referred_by': 'Referred by',
      // Reports
      'filters': 'Filters',
      'date_from': 'From',
      'date_to': 'To',
      'orders_by_status': 'Orders by Status',
      'payment_distribution': 'Payment Distribution',
      'units_sold': 'Units Sold',
      'no_retailer_data': 'No retailer data',
      'no_product_data': 'No product data',
      'no_payment_data': 'No payment data available',
      'no_status_data': 'No status data available',
      'no_sales_period': 'No sales in this period',
      'apply': 'Apply',
      'print': 'Print',
      'unable_load_report': 'Unable to load report',
      'reset': 'Reset',
      'title_template': 'Title Template',
      'body_template': 'Body Template',
      'retry': 'Retry',
      // Retailer Catalog
      'added_to_cart_success': '{name} added to cart!',
      'added_success': '{name} added!',
      'add_more_to_cart': 'Add More to Cart',
      'add_to_cart': 'Add to Cart',
      'product_catalog': 'Product Catalog',
      'search_products_hint': 'Search products by name or SKU...',
      'in_stock_qty': 'In Stock ({qty} available)',
      'low_stock_warning': 'Low Stock ({qty} left)',
      // Distributor Deliveries
      'no_deliveries_section': 'No deliveries in this section',
      'task_label': 'Task',
      'no_delivery_address': 'No delivery address',
      'value': 'Value',
      'status_failed': 'Failed',
      // Distributor Deliveries Detail
      'photo_attached': 'Proof photo attached.',
      'camera_open_error': 'Unable to open camera',
      'start_transit_first': 'Please start the transit first!',
      'collect_signature_first': 'Please collect a customer signature.',
      'capture_photo_first': 'Please capture a proof of delivery photo.',
      'invalid_payment_amount':
          'Invalid payment amount. Max allowed is {amount} DH',
      'delivery_completed_success': 'Delivery Completed & Recorded!',
      'delivery_label': 'Delivery',
      'retailer_destination': 'Retailer Destination',
      'photo_proof_label': 'Photo Proof of Delivery',
      'opening_camera': 'Opening camera...',
      'attach_delivery_photo': 'Attach Delivery Photo',
      'cash_payment_collection': 'Cash Payment Collection',
      'cash_collection_disabled_msg':
          'Cash collection is disabled for your account. Complete delivery without recording payment.',
      'cash_collection_admin_msg':
          'An admin can enable cash collection access for drivers or responsible staff.',
      'transit_started_msg': 'Transit started. Drive safely!',
      'start_delivery_action': 'Start Delivery (Start Transit)',
      'delivery_failed_msg': 'Delivery marked as failed.',
      'mark_failed_action': 'Mark Failed',
      'submit_delivery_action': 'Submit Delivery',
      'delivery_completed_success_banner': 'Delivery Completed Successfully',
      // Dashboard View
      'total_revenue': 'Total Revenue',
      'open_reports': 'Open reports',
      'active_shops': 'Active Shops',
      'view_all_orders': 'View all orders',
      'unpaid_balance': 'Unpaid Balance',
      'details': 'Details',
      'delivery_proof_tab': 'Delivery Proof',
      'click_view_lists': 'Click to view lists',
      'sales_performance_trend': 'Sales Performance Trend',
      'revenue_analytics_subtitle': 'Monthly revenue analytics in DH',
      'recent_system_activity': 'Recent System Activity',
      'outstanding_balances_title': 'Outstanding Balances',
      'total_outstanding_awaiting':
          'Total outstanding balance awaiting payments.',
      'no_outstanding_payments': 'No outstanding payments!',
      // Sales Representatives View
      'sales_representatives': 'Sales Representatives',
      'sales_representatives_subtitle':
          'Performance rankings and referral codes tracking',
      'referral_label': 'Referral: {code}',
      'counted_sales': 'Counted sales',
      'counted_orders': 'Counted Orders',
      'rep_features': 'Representative Features',
      'feature_dashboard': 'Dashboard sales view',
      'feature_retailers': 'Assigned retailers',
      'feature_orders': 'Scoped orders',
      'feature_onboarding': 'Retailer onboarding',
      'sales_counted_rep': 'Sales Counted For This Rep',
      'no_counted_orders_msg':
          'No non-cancelled orders from assigned retailers yet.',
      'cash_collection_access': 'Cash Collection Access',
      'cash_collection_access_desc':
          'Only enabled drivers or responsible staff can record cash collected from customers.',
      'no_cash_collectors_msg':
          'No eligible drivers or responsible staff found.',
      'create_user_account': 'Create User Account',
      'role_admin': 'Manager (Admin)',
      'role_sales_rep': 'Sales Rep',
      'role_distributor': 'Distributor',
      'role_retailer': 'Retailer (Shop)',
      'full_name': 'Full Name',
      'error_full_name': 'Please enter full name',
      'error_phone_number': 'Please enter phone number',
      'error_address': 'Please enter address',
      'enable_cash_collection': 'Enable cash collection',
      // Reports View Upgrades
      'analytics': 'Analytics & Metrics',
      'filtered_orders': 'Filtered Orders',
      'total_filtered': 'Total: {amount} DH',
      'show_filters': 'Show Filters',
      'hide_filters': 'Hide Filters',
      // Order History & Tracking
      'order_history': 'Order History & Tracking',
      'carrier_label': 'Carrier: {name}',
      'items_count': '{count} Items',
      // Notification Templates
      'template_activated': 'Template activated',
      'template_deactivated': 'Template deactivated',
      'failed_update_status': 'Failed to update status',
      'edit_template': 'Edit Template',
      'title_body_required': 'Title and body are required',
      'save_failed': 'Save failed',
      'saving': 'Saving...',
      'template_updated': 'Template updated successfully',
      'all_types_exist': 'All event types already have templates',
      'new_notification_template': 'New Notification Template',
      'event_type_required': 'Event type is required',
      'create_failed': 'Create failed',
      'creating': 'Creating...',
      'template_created': 'Template created successfully',
      'variables': 'Variables',
      'copied_variable': 'Copied',
      'new_template': 'New Template',
      'notification_templates': 'Notification Templates',
      'templates': 'templates',
      'active': 'active',
      'inactive': 'inactive',
      'loading_templates': 'Loading templates...',
      'something_wrong': 'Something went wrong',
      'no_templates_yet': 'No templates yet',
      'create_first_template':
          'Create your first notification template to start customizing alerts.',
      'create_template': 'Create Template',
      'tap_to_edit': 'Tap to edit',
      'event_product_new': 'New Product',
      'event_product_restocked': 'Product Restocked',
      'event_promotion_new': 'New Promotion',
      'event_promotion_updated': 'Promotion Updated',
      'event_order_placed': 'Order Placed',
      'event_order_shipped': 'Order Shipped',
      'event_payment_received': 'Payment Received',
      'reject_order': 'Reject Order',
      'reject_order_confirm': 'Are you sure you want to reject order',
      'reject': 'Reject',
      'order_rejected': 'Order rejected',
      'failed_reject_order': 'Failed to reject order',
    },
    'ar': {
      'app_title': 'حلوات للمعاملات',
      'app_title_ar': 'حلوات للمعاملات',
      'app_subtitle':
          'نظام ERP و CRM للمتاجر والمخزون والمبيعات والفواتير والتوزيع',
      'login': 'تسجيل الدخول',
      'email': 'البريد الإلكتروني',
      'email_or_phone': 'البريد الإلكتروني أو رقم الهاتف',
      'password': 'كلمة المرور',
      'dashboard': 'لوحة التحكم',
      'reports': 'التقارير',
      'orders': 'الطلبات',
      'crm': 'إدارة العملاء',
      'dispatch': 'التوزيع',
      'approvals': 'الموافقات',
      'onboard_shop': 'إضافة متجر',
      'catalog': 'الكتالوج',
      'inventory': 'المخزون',
      'procurement': 'المشتريات',
      'promotions': 'العروض',
      'notifications': 'الإشعارات',
      'audit_log': 'سجل التدقيق',
      'invoices': 'الفواتير',
      'sales_reps': 'مندوبي المبيعات',
      'settings': 'الإعدادات',
      'logout': 'تسجيل الخروج',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'loading': 'جاري التحميل...',
      'success': 'تم بنجاح',
      'error': 'خطأ',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'reset_password': 'إعادة تعيين كلمة المرور',
      'reset_password_for': 'إعادة تعيين كلمة مرور {name}',
      'password_reset_explanation':
          'سيستخدم المستخدم كلمة المرور هذه عند تسجيل الدخول في المرة القادمة.',
      'new_password': 'كلمة المرور الجديدة',
      'confirm_password': 'تأكيد كلمة المرور',
      'password_min_8': 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل',
      'confirm_password_required': 'أكد كلمة المرور',
      'passwords_do_not_match': 'كلمتا المرور غير متطابقتين',
      'password_updated_for': 'تم تحديث كلمة مرور {name}.',
      'password_update_failed': 'تعذر تحديث كلمة المرور.',
      'login_required': 'يرجى تسجيل الدخول قبل إرسال الطلب.',
      'order_place_failed': 'تعذر إرسال الطلب. تم الاحتفاظ بمحتويات السلة.',
      'order_placed': 'تم إرسال الطلب',
      'order_created_waiting_approval':
          'تم إنشاء الطلب {order} وهو بانتظار موافقة الإدارة.',
      'scheduled_delivery': 'موعد التسليم المبرمج',
      'ok': 'حسناً',
      'shopping_cart': 'سلة التسوق',
      'cart_empty': 'سلة التسوق فارغة',
      'cart_empty_hint': 'انتقل إلى الكتالوج لإضافة المنتجات.',
      'unit': 'للوحدة',
      'subtotal': 'المجموع الفرعي',
      'stock_limit_reached': 'لا يمكن تجاوز الكمية المتوفرة في المخزون.',
      'total_quantity': 'إجمالي الكمية',
      'place_order': 'إرسال الطلب',
      'cash_balance_outstanding': 'الرصيد النقدي والمبالغ المستحقة',
      'total_ordered': 'إجمالي الطلبات',
      'cash_collection_status': 'حالة تحصيل المبالغ',
      'no_payment_transactions': 'لا توجد معاملات دفع',
      'collected': 'المبلغ المحصل',
      'cash_collected_by_responsible':
          'يتم تحصيل المبلغ النقدي من طرف السائق أو الموظف المسؤول.',
      'ordered_items': 'المنتجات المطلوبة',
      'no_order_items': 'لم يتم إرجاع عناصر الطلب.',
      'settings_load_failed': 'تعذر تحميل الإعدادات',
      'logo_upload_failed': 'تعذر رفع شعار الشركة.',
      'company_settings_saved': 'تم حفظ إعدادات الشركة.',
      'company_settings_save_failed': 'تعذر حفظ إعدادات الشركة',
      'otp_login_enabled_message': 'تم تفعيل تسجيل الدخول برمز OTP.',
      'otp_login_disabled_message': 'تم إيقاف تسجيل الدخول برمز OTP.',
      'otp_update_failed': 'تعذر تحديث إعداد تسجيل الدخول برمز OTP',
      'company_profile': 'ملف الشركة',
      'login_and_otp': 'تسجيل الدخول ورمز OTP',
      'upload_company_logo': 'رفع شعار الشركة',
      'invoice_logo_hint':
          'سيظهر هذا الشعار ومعلومات الشركة في الفواتير المطبوعة.',
      'company_name': 'اسم الشركة',
      'tax_id': 'المعرف الضريبي / ICE',
      'otp_login': 'تسجيل الدخول برمز OTP',
      'otp_login_control_description':
          'السماح للمستخدمين المسجلين في هذه الشركة بالدخول عبر رمز SMS أو WhatsApp.',
      'otp_existing_user_explanation':
          'رمز OTP لا ينشئ حساباً جديداً. بعد التحقق يتم تسجيل رقم الهاتف في حسابه المسجل مسبقاً.',
      'create': 'إنشاء',
      'add': 'إضافة',
      'delete': 'حذف',
      'search': 'بحث',
      'import': 'استيراد',
      'export': 'تصدير',
      'bulk_import': 'استيراد جماعي',
      'bulk_export': 'تصدير جماعي',
      'categories': 'الفئات',
      'brands': 'العلامات التجارية',
      'products': 'المنتجات',
      'retailers': 'تجار التجزئة',
      'customers': 'العملاء',
      'accounts': 'الحسابات',
      'recent_activity': 'النشاط الأخير',
      'sales_performance': 'أداء المبيعات',
      'target_progress': 'التقدم نحو الهدف',
      'user_role': 'دور المستخدم',
      'name': 'الاسم',
      'phone': 'رقم الهاتف',
      'manager': 'المدير',
      'sales_rep': 'مندوب المبيعات',
      'distributor': 'الموزع',
      'retailer': 'تاجر التجزئة',
      'create_account': 'إنشاء حساب مستخدم',
      'low_stock': 'مخزون منخفض',
      'adjust_stock': 'تعديل المخزون',
      'reason': 'السبب',
      'amount': 'المبلغ',
      'status': 'الحالة',
      'due_date': 'تاريخ الاستحقاق',
      'mark_all_read': 'تحديد الكل كمقروء',
      'no_items': 'لا توجد عناصر',
      'add_category': 'إضافة فئة',
      'category_name': 'اسم الفئة',
      'upload_image': 'رفع صورة',
      'image_uploaded': 'تم رفع الصورة',
      'add_brand': 'إضافة علامة تجارية',
      'brand_name': 'اسم العلامة التجارية',
      'upload_logo': 'رفع الشعار',
      'logo_uploaded': 'تم رفع الشعار',
      'add_product': 'إضافة منتج',
      'product_name': 'اسم المنتج',
      'base_price': 'السعر الأساسي',
      'price': 'السعر',
      'category': 'الفئة',
      'brand': 'العلامة التجارية',
      'new_promotion': 'عرض جديد',
      'type': 'النوع',
      'percentage': 'نسبة مئوية',
      'fixed_amount': 'مبلغ ثابت',
      'bulk_tier': 'خصم حسب الكمية',
      'buy_x_get_y': 'اشتر X واحصل على Y',
      'priority': 'الأولوية',
      'all': 'الكل',
      'paid': 'مدفوع',
      'unpaid': 'غير مدفوع',
      'outstanding': 'المتبقي',
      'gross_sales': 'إجمالي المبيعات',
      'top_retailers': 'أفضل التجار',
      'top_products': 'أفضل المنتجات',
      'sales_trend': 'اتجاه المبيعات',
      'detailed_reports': 'تقارير تفصيلية',
      'target_scope': 'نطاق العرض',
      'product_specific': 'خاص بمنتج',
      'brand_specific': 'خاص بعلامة تجارية',
      'category_specific': 'خاص بفئة',
      'sign_out': 'تسجيل الخروج',
      'sign_out_confirm': 'هل تريد تسجيل الخروج؟',
      'press_back_exit': 'اضغط رجوع مرة أخرى للخروج',
      'back_to_home': 'العودة إلى الصفحة الرئيسية',
      'retailer_portal': 'بوابة التاجر',
      'distributor_portal': 'بوابة الموزع',
      'representative_workspace': 'مساحة عمل المندوب',
      'assigned_retailers': 'التجار المعينون',
      'orders_cash': 'الطلبات والتحصيل',
      'onboard': 'إضافة',
      'cart': 'السلة',
      'payments': 'المدفوعات',
      'refresh': 'تحديث',
      'main': 'الرئيسية',
      'management': 'الإدارة',
      'system': 'النظام',
      'address': 'العنوان',
      'latitude': 'خط العرض',
      'longitude': 'خط الطول',
      'required': 'مطلوب',
      'invalid': 'غير صالح',
      'verify_location_on_map': 'تأكيد الموقع على الخريطة',
      'verify_shop_location': 'تأكيد موقع المتجر',
      'close': 'إغلاق',
      'use_current_location': 'استخدام موقعي الحالي',
      'use_this_pin': 'استخدام هذا الدبوس',
      'location_help': 'اضغط على الخريطة لتحريك الدبوس، أو استخدم موقع الجهاز.',
      'location_services_disabled':
          'خدمات الموقع غير مفعلة. شغل GPS ثم حاول مرة أخرى.',
      'turn_on_location_retry':
          'تم فتح إعدادات الموقع. شغل GPS ثم اضغط استخدام موقعي الحالي مرة أخرى.',
      'location_permission_denied': 'لم يتم منح إذن الموقع.',
      'location_permission_settings':
          'إذن الموقع محظور. فعله من إعدادات تطبيق أندرويد.',
      'map_unavailable':
          'الخريطة غير متاحة الآن. أعد فتح الشاشة أو غير الاتجاه.',
      'no_delivery_coordinates': 'لا توجد إحداثيات تسليم محفوظة',
      'gps_unavailable': 'GPS: غير متاح',
      'delivery_pin_saved': 'تم حفظ دبوس التسليم',
      'location_needed': 'الموقع مطلوب',
      'locating_driver': 'جار تحديد موقع السائق...',
      'direct_route_preview': 'معاينة المسار المباشر',
      'open_road_navigation': 'فتح الملاحة على الطريق',
      'navigation_open_failed': 'تعذر فتح تطبيق الملاحة.',
      'retry_location': 'إعادة محاولة تحديد الموقع',
      'password_login': 'كلمة المرور',
      'phone_otp': 'رمز الهاتف',
      'new_retailer': 'تاجر جديد؟',
      'register_here': 'سجل هنا',
      'phone_number': 'رقم الهاتف',
      'six_digit_code': 'رمز من 6 أرقام',
      // Order Statuses
      'status_pending': 'قيد الانتظار',
      'status_approved': 'تمت الموافقة',
      'status_in_transit': 'جاري التوصيل',
      'status_delivered': 'تم التوصيل',
      'status_cancelled': 'ملغي',
      // Payment Statuses
      'payment_unpaid': 'غير مدفوع',
      'payment_partially_paid': 'مدفوع جزئياً',
      'payment_paid': 'مدفوع',
      // Order details and labels
      'order_label': 'طلب',
      'client_information': 'معلومات العميل',
      'coordinates': 'الإحداثيات',
      'assigned_to': 'معين إلى',
      'awaiting_assignment': 'في انتظار التعيين',
      'order_items': 'عناصر الطلب',
      'grand_total': 'الإجمالي الكلي',
      'payment_summary': 'ملخص الدفع',
      'total_amount': 'المبلغ الإجمالي',
      'remaining_balance': 'المبلغ المتبقي',
      'delivery_proof': 'إثبات التسليم',
      'no_delivery_proof': 'لا يوجد إثبات تسليم مرفق',
      'delivery_photo': 'صورة التسليم',
      'failed_load_image': 'فشل في تحميل الصورة',
      'delivery_signature': 'توقيع التسليم',
      'failed_load_signature': 'فشل في تحميل التوقيع',
      'notes': 'ملاحظات',
      'product': 'المنتج',
      'qty': 'الكمية',
      'unit_price': 'سعر الوحدة',
      'total': 'الإجمالي',
      'item': 'عنصر',
      'items': 'عناصر',
      // CRM
      'pin': 'موقع المتجر',
      'missing': 'غير متوفر',
      'recent_orders': 'الطلبات الأخيرة',
      'no_orders_yet': 'لا توجد طلبات بعد',
      'open_orders': 'الطلبات المفتوحة',
      'pin_missing': 'موقع مفقود',
      'crm_load_failed': 'فشل تحميل إدارة العملاء',
      'search_crm': 'البحث في العملاء',
      'clear': 'خالص',
      'due_status': 'مستحق',
      'approve_account': 'موافقة',
      'account_approved': 'تمت الموافقة على الحساب بنجاح.',
      'approval_failed': 'فشلت الموافقة على الحساب',
      'registrations': 'طلبات التسجيل',
      'pending_registrations': 'طلبات التسجيل المعلقة',
      'registration_review_help':
          'راجع حسابات التجار الجدد قبل السماح لهم بتسجيل الدخول.',
      'search_registrations': 'ابحث بالمتجر أو البريد أو الهاتف أو العنوان',
      'no_pending_registrations': 'لا توجد طلبات في الانتظار',
      'no_pending_registrations_help':
          'ستظهر طلبات التجار الجديدة هنا للموافقة عليها.',
      'approve_registration': 'الموافقة على التسجيل',
      'approve_registration_confirm':
          'هل تريد الموافقة على {name} والسماح لهذا الحساب بالدخول؟',
      'reject_registration': 'رفض التسجيل',
      'reject_registration_confirm':
          'هل تريد رفض {name}؟ سيبقى الحساب غير نشط.',
      'rejection_reason': 'السبب (اختياري)',
      'rejection_reason_hint': 'أضف ملاحظة إلى سجل التدقيق',
      'registration_rejected': 'تم رفض طلب التسجيل.',
      'rejection_failed': 'فشل رفض طلب التسجيل',
      'submitted': 'تاريخ الطلب',
      'referred_by': 'تمت الإحالة بواسطة',
      // Reports
      'filters': 'تصفية',
      'date_from': 'من',
      'date_to': 'إلى',
      'orders_by_status': 'الطلبات حسب الحالة',
      'payment_distribution': 'توزيع المدفوعات',
      'units_sold': 'الوحدات المباعة',
      'no_retailer_data': 'لا توجد بيانات للتجار',
      'no_product_data': 'لا توجد بيانات للمنتجات',
      'no_payment_data': 'لا توجد بيانات دفع متاحة',
      'no_status_data': 'لا توجد بيانات حالة متاحة',
      'no_sales_period': 'لا توجد مبيعات في هذه الفترة',
      'apply': 'تطبيق',
      'print': 'طباعة',
      'unable_load_report': 'فشل في تحميل التقرير',
      'reset': 'إعادة تعيين',
      'title_template': 'قالب العنوان',
      'body_template': 'قالب المحتوى',
      'retry': 'إعادة المحاولة',
      // Retailer Catalog
      'added_to_cart_success': 'تم إضافة {name} إلى السلة!',
      'added_success': 'تم إضافة {name}!',
      'add_more_to_cart': 'إضافة المزيد إلى السلة',
      'add_to_cart': 'إضافة إلى السلة',
      'product_catalog': 'كتالوج المنتجات',
      'search_products_hint': 'البحث عن المنتجات بالاسم أو رمز SKU...',
      'in_stock_qty': 'متوفر (متوفر {qty})',
      'low_stock_warning': 'كمية منخفضة (متبقي {qty})',
      // Distributor Deliveries
      'no_deliveries_section': 'لا توجد عمليات توصيل في هذا القسم',
      'task_label': 'المهمة',
      'no_delivery_address': 'لا يوجد عنوان توصيل',
      'value': 'القيمة',
      'status_failed': 'فشلت',
      // Distributor Deliveries Detail
      'photo_attached': 'تم إرفاق صورة الإثبات.',
      'camera_open_error': 'فشل في فتح الكاميرا',
      'start_transit_first': 'يرجى بدء الرحلة أولاً!',
      'collect_signature_first': 'يرجى الحصول على توقيع العميل.',
      'capture_photo_first': 'يرجى التقاط صورة إثبات التوصيل.',
      'invalid_payment_amount':
          'مبلغ الدفع غير صالح. الحد الأقصى المسموح به هو {amount} درهم',
      'delivery_completed_success': 'تم اكتمال التوصيل وتسجيله بنجاح!',
      'delivery_label': 'التوصيل',
      'retailer_destination': 'وجهة التاجر',
      'photo_proof_label': 'إثبات التوصيل بالصورة',
      'opening_camera': 'جاري فتح الكاميرا...',
      'attach_delivery_photo': 'إرفاق صورة التوصيل',
      'cash_payment_collection': 'تحصيل الدفع النقدي',
      'cash_collection_disabled_msg':
          'تحصيل المبالغ النقدية معطل لحسابك. أكمل التوصيل دون تسجيل الدفع.',
      'cash_collection_admin_msg':
          'يمكن للمسؤول تمكين صلاحية تحصيل المبالغ النقدية للسائقين أو الموظفين المعنيين.',
      'transit_started_msg': 'بدأت الرحلة. قد بحذر!',
      'start_delivery_action': 'بدء التوصيل (بدء الرحلة)',
      'delivery_failed_msg': 'تم تحديد التوصيل كفاشل.',
      'mark_failed_action': 'تحديد كفاشل',
      'submit_delivery_action': 'إرسال التوصيل',
      'delivery_completed_success_banner': 'تم التوصيل بنجاح',
      // Dashboard View
      'total_revenue': 'إجمالي الإيرادات',
      'open_reports': 'فتح التقارير',
      'active_shops': 'المحلات النشطة',
      'view_all_orders': 'عرض جميع الطلبات',
      'unpaid_balance': 'الصيد غير المدفوع',
      'details': 'التفاصيل',
      'delivery_proof_tab': 'إثبات التوصيل',
      'click_view_lists': 'اضغط لعرض القوائم',
      'sales_performance_trend': 'اتجاه أداء المبيعات',
      'revenue_analytics_subtitle': 'تحليلات الإيرادات الشهرية بالدرهم',
      'recent_system_activity': 'نشاط النظام الأخير',
      'outstanding_balances_title': 'الأرصدة المستحقة',
      'total_outstanding_awaiting': 'إجمالي المبالغ المستحقة بانتظار السداد.',
      'no_outstanding_payments': 'لا توجد مبالغ مستحقة!',
      // Sales Representatives View
      'sales_representatives': 'مندوبي المبيعات',
      'sales_representatives_subtitle': 'ترتيب الأداء وتتبع رموز الإحالة',
      'referral_label': 'رمز الإحالة: {code}',
      'counted_sales': 'المبيعات المحتسبة',
      'counted_orders': 'الطلب المحتسب',
      'rep_features': 'ميزات المندوب',
      'feature_dashboard': 'عرض لوحة تحكم المبيعات',
      'feature_retailers': 'التجار المعينين',
      'feature_orders': 'الطلبات المخصصة',
      'feature_onboarding': 'تسجيل التجار الجدد',
      'sales_counted_rep': 'المبيعات المحتسبة لهذا المندوب',
      'no_counted_orders_msg':
          'لا توجد طلبات غير ملغاة من التجار المعينين بعد.',
      'cash_collection_access': 'صلاحية تحصيل النقد',
      'cash_collection_access_desc':
          'فقط السائقين أو الموظفين المفعلين يمكنهم تسجيل المبالغ النقدية المحصلة.',
      'no_cash_collectors_msg': 'لم يتم العثور على سائقين أو موظفين مؤهلين.',
      'create_user_account': 'إنشاء حساب مستخدم',
      'role_admin': 'مدير (مسؤول)',
      'role_sales_rep': 'مندوب مبيعات',
      'role_distributor': 'موزع',
      'role_retailer': 'تاجر تجزئة (محل)',
      'full_name': 'الاسم الكامل',
      'error_full_name': 'يرجى إدخال الاسم الكامل',
      'error_phone_number': 'يرجى إدخال رقم الهاتف',
      'error_address': 'يرجى إدخال العنوان',
      'enable_cash_collection': 'تفعيل تحصيل النقد',
      // Reports View Upgrades
      'analytics': 'التحليلات والمؤشرات',
      'filtered_orders': 'الطلبات المفلترة',
      'total_filtered': 'الإجمالي: {amount} درهم',
      'show_filters': 'عرض التصفية',
      'hide_filters': 'إخفاء التصفية',
      // Order History & Tracking
      'order_history': 'سجل الطلبات وتتبعها',
      'carrier_label': 'الناقل: {name}',
      'items_count': '{count} منتجات',
      // Notification Templates
      'template_activated': 'تم تفعيل القالب بنجاح',
      'template_deactivated': 'تم إلغاء تفعيل القالب بنجاح',
      'failed_update_status': 'فشل في تحديث الحالة',
      'edit_template': 'تعديل القالب',
      'title_body_required': 'العنوان والمحتوى مطلوبان',
      'save_failed': 'فشل الحفظ',
      'saving': 'جاري الحفظ...',
      'template_updated': 'تم تحديث القالب بنجاح',
      'all_types_exist': 'جميع أنواع الأحداث لديها قوالب بالفعل',
      'new_notification_template': 'قالب إشعارات جديد',
      'event_type_required': 'نوع الحدث مطلوب',
      'create_failed': 'فشل الإنشاء',
      'creating': 'جاري الإنشاء...',
      'template_created': 'تم إنشاء القالب بنجاح',
      'variables': 'المتغيرات',
      'copied_variable': 'تم النسخ',
      'new_template': 'قالب جديد',
      'notification_templates': 'قوالب الإشعارات',
      'templates': 'قوالب',
      'active': 'نشط',
      'inactive': 'غير نشط',
      'loading_templates': 'جاري تحميل القوالب...',
      'something_wrong': 'حدث خطأ ما',
      'no_templates_yet': 'لا توجد قوالب بعد',
      'create_first_template': 'أنشئ أول قالب إشعارات لبدء تخصيص التنبيهات.',
      'create_template': 'إنشاء قالب',
      'tap_to_edit': 'انقر للتعديل',
      'event_product_new': 'منتج جديد',
      'event_product_restocked': 'إعادة توفر المنتج',
      'event_promotion_new': 'عرض جديد',
      'event_promotion_updated': 'تحديث العرض',
      'event_order_placed': 'تم تقديم الطلب',
      'event_order_shipped': 'تم شحن الطلب',
      'event_payment_received': 'تم استلام الدفع',
      'reject_order': 'رفض الطلب',
      'reject_order_confirm': 'هل أنت متأكد أنك تريد رفض الطلب',
      'reject': 'رفض',
      'order_rejected': 'تم رفض الطلب',
      'failed_reject_order': 'فشل رفض الطلب',
    },
  };

  String translate(String key) {
    return _localizedValues[_locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}
